"""deleted

Revision ID: b8fab437652a
Revises: 610609750797
Create Date: 2025-01-02 01:38:12.556659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fab437652a'
down_revision: Union[str, None] = '610609750797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'novel_tags', ['novel_id', 'tag_id'])
    op.add_column('novels', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.create_index(op.f('ix_novels_deleted'), 'novels', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novels_deleted'), table_name='novels')
    op.drop_column('novels', 'deleted')
    op.drop_constraint(None, 'novel_tags', type_='unique') # type: ignore
    # ### end Alembic commands ###
