"""init

Revision ID: cf075b138dfd
Revises: 
Create Date: 2025-01-08 17:12:22.380158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf075b138dfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_excluded_tags_name')
    )
    op.create_table('novels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('site', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_novels_source_url')
    )
    op.create_index(op.f('ix_novels_deleted'), 'novels', ['deleted'], unique=False)
    op.create_index('ix_novels_excluded', 'novels', ['excluded'], unique=False)
    op.create_index(op.f('ix_novels_source_url'), 'novels', ['source_url'], unique=True)
    op.create_table('search_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_search_tags_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_chapters_source_url')
    )
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_index('ix_chapters_posted_at', 'chapters', ['posted_at'], unique=False)
    op.create_table('novel_tags',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'tag_id'),
    sa.UniqueConstraint('novel_id', 'tag_id')
    )
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapter_histories_chapter_id', 'chapter_histories', ['chapter_id'], unique=False)
    op.create_index('ix_chapter_histories_posted_at', 'chapter_histories', ['posted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_histories_posted_at', table_name='chapter_histories')
    op.drop_index('ix_chapter_histories_chapter_id', table_name='chapter_histories')
    op.drop_table('chapter_histories')
    op.drop_table('scrape_logs')
    op.drop_table('novel_tags')
    op.drop_index('ix_chapters_posted_at', table_name='chapters')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('tags')
    op.drop_table('search_tags')
    op.drop_index(op.f('ix_novels_source_url'), table_name='novels')
    op.drop_index('ix_novels_excluded', table_name='novels')
    op.drop_index(op.f('ix_novels_deleted'), table_name='novels')
    op.drop_table('novels')
    op.drop_table('excluded_tags')
    # ### end Alembic commands ###
