name: run_script
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 毎日午前0時に実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Pythonバージョンのキャッシュ
      - name: "Cache: Cache Python"
        id: python-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      # pipキャッシュを取得または保存する
      - name: "Shell: Get pip cache dir"
        id: pip-cache-dir
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install -U wheel
          echo "pip-cache-dir=$(pip cache dir)" >> $GITHUB_ENV

      - name: "Cache: Cache pip"
        if: steps.python-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ${{ env.pip-cache-dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 依存関係のインストール（キャッシュがない場合）
      - name: Install dependencies
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
          SUPABASE_DB_PASS: ${{ secrets.SUPABASE_DB_PASS }}
          SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
          SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
          NOCTURNE_RANKED_URL: ${{ secrets.NOCTURNE_RANKED_URL }}
          NOCTURNE_TAG_SEARCH_URL: ${{ secrets.NOCTURNE_TAG_SEARCH_URL }}
        run: |
          python main.py